name: Deploy Node.js Backend

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Change Directory to Backend
        run: cd backend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t oyshipsarker/mern-stack-app -f Dockerfile .

      - name: Publish Image to Docker Hub
        run: docker push oyshipsarker/mern-stack-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull oyshipsarker/mern-stack-app:latest

      - name: List Docker Images
        run: docker images

      - name: Stop and Remove Existing Container (if any)
        run: |
          docker stop mern-stack-app-container || true
          docker rm mern-stack-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 \
            --name mern-stack-app-container \
            -e MONGODB_URL="${{ secrets.MONGO_URL }}" \
            -e OPEN_AI_SECRET="${{ secrets.OPEN_AI_SECRET }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e COOKIE_SECRET="${{ secrets.COOKIE_SECRET }}" \
            -e OPENAI_ORGANIZATION_ID="${{ secrets.OPENAI_ORGANIZATION_ID }}" \
            oyshipsarker/mern-stack-app:latest
